<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Library</OutputType></PropertyGroup>
  <ItemGroup>
    <Compile Include="Value.fs" />
    <Compile Include="Sandbox.fs" />
    <Compile Include="Interpreter.fs" />
    <Compile Include="StepValueUse.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Fogell.Groovy/Fogell.Groovy.fsproj" />
    <ProjectReference Include="../Fogell.Admission/Fogell.Admission.fsproj" />
  </ItemGroup>
</Project>
