<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Library</OutputType></PropertyGroup>
  <ItemGroup>
    <Compile Include="Lexeme.fs" />
    <Compile Include="Parser.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Fogell.Ir/Fogell.Ir.fsproj" />
    <ProjectReference Include="../Fogell.Admission/Fogell.Admission.fsproj" />
    <PackageReference Include="FParsec" Version="1.1.1" />
  </ItemGroup>
</Project>
