<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>fogell-score</AssemblyName>
  </PropertyGroup>
  <ItemGroup><Compile Include="Program.fs" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Fogell.Pipeline.Parser/Fogell.Pipeline.Parser.fsproj" />
  </ItemGroup>
</Project>
