<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Library</OutputType></PropertyGroup>
  <ItemGroup>
    <Compile Include="Records.fs" />
    <Compile Include="Journal.fs" />
    <Compile Include="Resume.fs" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="../Fogell.Domain/Fogell.Domain.fsproj" /></ItemGroup>
</Project>
