#!/usr/bin/env bb
;; FG-090/091/092. Generates the compatibility scorecard, the machine-readable
;; ledger, and KNOWN-LIMITATIONS.md — from evidence on disk, never by hand.
;;
;; ADR 0001 fixes three tiers and forbids collapsing them into one number, with the
;; reason recorded: a prior engine had 146 non-empty IRs and 5 files of proven
;; parity, and a single percentage would have implied 64%.
;;
;; THE SAME TRAP IS LIVE IN THIS REPO RIGHT NOW. There are 118 differential receipts
;; and 228 corpus files, and the NAME OVERLAP BETWEEN THEM IS ZERO: every receipt is
;; for a hand-written case in `differential/cases`, not for a corpus Jenkinsfile.
;; Printing "118 proven" anywhere near "228 files" invites 118/228 = 52%, and the
;; true corpus figure for proven parity is 0 of 228. The two populations are
;; therefore reported in SEPARATE SECTIONS, each with its own denominator stated on
;; the same line as its count, and no ratio is ever computed.
;;
;; Parse only. Corpus files are untrusted third-party CI code: this reads and parses
;; them and never executes one.
;;
;;   usage: scripts/generate-scorecard.bb [--check]
;;          --check regenerates into a temp dir and fails if the committed
;;          artifacts differ, so a stale scorecard cannot survive a gate run

(require '[babashka.fs :as fs] '[babashka.process :as p] '[clojure.string :as str])

(let [check? (some #{"--check"} *command-line-args*)
      root (str (fs/parent (fs/parent (fs/absolutize *file*))))
      corpus (or (System/getenv "FOGELL_CORPUS")
                 "/sn8100/work/exchange/crucible-gate/corpus")

      ;; THE CORPUS GATE RUNS FIRST, as its own header demands. A drifted corpus
      ;; invalidates every count below it, so a scorecard generated over one is
      ;; worse than none — it looks authoritative and is not.
      gate (p/shell {:dir root :out :string :err :string :continue true}
                    "scripts/verify-corpus.sh")
      _ (when-not (zero? (:exit gate))
          (println "FAIL: corpus gate refused; no scorecard generated")
          (println (str/trim (str (:out gate) (:err gate))))
          (System/exit 1))

      score (p/shell {:dir root :out :string :err :string :continue true}
                     "dotnet" "run" "--project" "tools/Fogell.Corpus.Score"
                     "-c" "Release" "--no-build" "--" corpus)
      _ (when-not (zero? (:exit score))
          (println "FAIL: corpus scorer did not run")
          (println (str/trim (str (:err score))))
          (System/exit 1))

      rows (->> (str/split-lines (:out score))
                (drop 1)
                (remove str/blank?)
                (map #(str/split % #"\t" -1))
                (map (fn [[file verdict code stages steps detail]]
                       {:file file :verdict verdict :code code
                        :stages stages :steps steps :detail detail})))

      ;; A receipt proves parity for the file it NAMES. Receipts are keyed by case
      ;; name; a corpus file earns tier 1 only if a receipt carries its exact name.
      receipts (->> (fs/glob (fs/file root "differential/receipts") "*.receipt.txt")
                    (map (fn [p]
                           (let [n (str/replace (fs/file-name p) ".receipt.txt" "")
                                 body (slurp (fs/file p))]
                             [n (if (re-find #"(?m)^VERDICT: PROVEN" body) :proven :other)])))
                    (into {}))

      tier-of (fn [{:keys [file verdict]}]
                (let [stem (str/replace file ".Jenkinsfile" "")]
                  (cond
                    (= :proven (get receipts stem)) 1
                    (contains? #{"err" "scripted-err"} verdict) 3
                    :else 2)))

      ledger (->> rows
                  (map (fn [r]
                         (let [t (tier-of r)]
                           (assoc r :tier t
                                  :evidence (case t
                                              1 (str "receipt:" (str/replace (:file r) ".Jenkinsfile" ""))
                                              3 (str (:code r) " " (:detail r))
                                              2 "parsed; execution not attempted (untrusted corpus)")))))
                  (sort-by :file))

      by-tier (group-by :tier ledger)
      t1 (count (get by-tier 1 []))
      t2 (count (get by-tier 2 []))
      t3 (count (get by-tier 3 []))
      total (count ledger)

      by-code (->> (get by-tier 3 [])
                   (group-by :code)
                   (map (fn [[c xs]] [c (count xs)]))
                   (sort-by (comp - second)))

      case-receipts (count receipts)
      case-proven (count (filter #(= :proven (val %)) receipts))

      ledger-tsv
      (str "# Compatibility ledger — generated by scripts/generate-scorecard.bb; do not edit\n"
           "# tier 1 = proven compatible (differential receipt names this file)\n"
           "# tier 2 = admitted (parses; execution NOT attempted — untrusted corpus)\n"
           "# tier 3 = rejected (named error code and source position)\n"
           "file\ttier\tcode\tevidence\n"
           (str/join "\n"
                     (map #(str (:file %) "\t" (:tier %) "\t"
                                (if (str/blank? (:code %)) "-" (:code %)) "\t"
                                (:evidence %))
                          ledger))
           "\n")

      ;; The rejection REASON, not just the code. All 79 tier-3 files carry the same
      ;; `malformed_syntax` code, which names nothing a reader can act on; the parser
      ;; message behind it does. Grouping by that message turns the corpus into a
      ;; RANKED WORK LIST instead of a wall of identical codes.
      reason-of (fn [{:keys [detail code]}]
                  (-> (or detail "")
                      (str/replace (re-pattern (str "^" (java.util.regex.Pattern/quote (or code "")) " ")) "")
                      (str/replace #"\s*@\d+:\d+\s*$" "")
                      str/trim))

      by-reason (->> (get by-tier 3 [])
                     (group-by reason-of)
                     (map (fn [[r xs]]
                            {:reason (if (str/blank? r) "(no message)" r)
                             :count (count xs)
                             :examples (->> xs (map :file) sort (take 3))}))
                     (sort-by (comp - :count)))

      limitations-md
      (str "# Known limitations\n\n"
           "Generated by `scripts/generate-scorecard.bb` from the compatibility ledger. Do not edit.\n\n"
           "Every entry is a corpus file Fogell REFUSED, with the parser's own message and the\n"
           "count of files hitting it. A refusal is a limitation stated out loud; ADR 0001 prefers\n"
           "it to a false success, and this file is where those refusals are published rather than\n"
           "left in a log.\n\n"
           "Denominator: " t3 " rejected of " total " corpus files. The remaining " t2
           " were ADMITTED (parsed) — which is not a parity claim, and " t1 " have proven parity.\n\n"
           (str/join "\n"
                     (map (fn [{:keys [reason count examples]}]
                            (str "## " reason "\n\n"
                                 "Files: **" count "**\n\n"
                                 (str/join "\n" (map #(str "- `" % "`") examples))
                                 (if (> count 3) (str "\n- …and " (- count 3) " more (see the ledger)") "")
                                 "\n"))
                          by-reason))
           "\n")

      scorecard-md
      (str "# Compatibility scorecard\n\n"
           "Generated by `scripts/generate-scorecard.bb` from evidence on disk. Do not edit.\n\n"
           "ADR 0001 fixes three tiers and forbids collapsing them into one number. "
           "**No percentage appears in this document**, and every count states its own denominator.\n\n"
           "## Corpus (third-party Jenkinsfiles, parse only)\n\n"
           "| Tier | Meaning | Count |\n|---|---|---|\n"
           "| 1 | proven compatible — a differential receipt names this file | " t1 " of " total " |\n"
           "| 2 | admitted — parses; **execution not attempted** (untrusted corpus) | " t2 " of " total " |\n"
           "| 3 | rejected — named error code and source position | " t3 " of " total " |\n\n"
           "Tier 2 is NOT a parity claim. It says the file was admitted, nothing more; "
           "these files are third-party CI code and are never executed here.\n\n"
           (if (seq by-code)
             (str "### Tier-3 rejections by code\n\n| Code | Files |\n|---|---|\n"
                  (str/join "\n" (map (fn [[c n]] (str "| `" c "` | " n " |")) by-code))
                  "\n\n")
             "")
           "## Differential case suite (hand-written cases — a DIFFERENT population)\n\n"
           "| Receipts | Proven |\n|---|---|\n| " case-receipts " | " case-proven " of " case-receipts " |\n\n"
           "**These two sections do not share a denominator.** The name overlap between the "
           "corpus and the receipt set is currently **zero**: every receipt proves a "
           "hand-written case, not a corpus file. Reading the receipt count against the corpus "
           "count would produce exactly the false ratio ADR 0001 was written to prevent — the "
           "prior engine's 146 IRs against 5 proven files, which a single percentage would have "
           "reported as 64%.\n")]

  (if check?
    (let [lp (fs/file root "docs/COMPATIBILITY-LEDGER.tsv")
          sp (fs/file root "docs/COMPATIBILITY-SCORECARD.md")
          stale (cond-> []
                  (or (not (fs/exists? lp)) (not= ledger-tsv (slurp lp))) (conj "docs/COMPATIBILITY-LEDGER.tsv")
                  (or (not (fs/exists? sp)) (not= scorecard-md (slurp sp))) (conj "docs/COMPATIBILITY-SCORECARD.md")
                  (let [kp (fs/file root "docs/KNOWN-LIMITATIONS.md")]
                    (or (not (fs/exists? kp)) (not= limitations-md (slurp kp)))) (conj "docs/KNOWN-LIMITATIONS.md"))]
      (if (seq stale)
        (do (println "FAIL: generated artifacts are stale — regenerate with scripts/generate-scorecard.bb")
            (doseq [f stale] (println "  " f))
            (System/exit 1))
        (println (str "scorecard artifacts current: tier1=" t1 " tier2=" t2 " tier3=" t3 " of " total
                      " corpus files; " case-proven "/" case-receipts " case receipts proven"))))
    (do
      (spit (fs/file root "docs/COMPATIBILITY-LEDGER.tsv") ledger-tsv)
      (spit (fs/file root "docs/COMPATIBILITY-SCORECARD.md") scorecard-md)
      (spit (fs/file root "docs/KNOWN-LIMITATIONS.md") limitations-md)
      (println (str "wrote docs/COMPATIBILITY-LEDGER.tsv and docs/COMPATIBILITY-SCORECARD.md"))
      (println (str "corpus: tier1=" t1 " tier2=" t2 " tier3=" t3 " of " total))
      (println (str "cases:  " case-proven " proven of " case-receipts " receipts (separate denominator)")))))
