#!/usr/bin/env bash
# FG-094. Offline proof for set-based compatibility non-regression.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
ROOT=$PWD
CHECKER="$ROOT/scripts/check-compatibility-regression.py"
if [ ! -f "$CHECKER" ] || [ ! -x "$CHECKER" ] || [ -L "$CHECKER" ]; then
  echo 'FG-094 proof REFUSED: repository checker is not an executable non-symlink file' >&2
  exit 1
fi

LAB=$(mktemp -d /tmp/fogell-fg094-proof.XXXXXX)
trap 'rm -rf "$LAB"' EXIT
REPO="$LAB/repo"
MOUNT="$LAB/mounted-corpus"
OUT="$LAB/output"
ORACLE="$OUT/oracle.tsv"
BASELINE="$OUT/baseline.json"
SCORECARD_MARKER="$OUT/scorecard-ran"
FAILED=0
mkdir -p "$REPO/scripts" "$REPO/docs" "$REPO/corpus" "$MOUNT" "$OUT"

sha256() { sha256sum "$1" | awk '{print $1}'; }

ledger_row() {
  local file=$1 tier=$2
  case "$tier" in
    1) printf '%s\t1\t-\treceipt:%s\n' "$file" "${file%.Jenkinsfile}" ;;
    admitted) printf '%s\tadmitted\t-\tparsed only\n' "$file" ;;
    3) printf '%s\t3\tmalformed_syntax\trefused at 1:1\n' "$file" ;;
    *) echo "bad proof tier: $tier" >&2; exit 2 ;;
  esac
}

write_ledger() {
  local path=$1 notready=$2 ready=$3 tierone=$4 vins=$5
  {
    printf '%s\n' \
      '# Compatibility ledger — generated by proof' \
      '# tier 1 = proven compatible' \
      '# admitted = parses only' \
      '# tier 3 = named refusal'
    printf 'file\ttier\tcode\tevidence\n'
    ledger_row notready.Jenkinsfile "$notready"
    ledger_row ready.Jenkinsfile "$ready"
    ledger_row tierone.Jenkinsfile "$tierone"
    ledger_row vinsguru_jenkins-pipeline.Jenkinsfile "$vins"
  } > "$path"
}

write_manifest() {
  local path=$1
  {
    printf '%064d  notready.Jenkinsfile\n' 0
    printf '%064d  ready.Jenkinsfile\n' 1
    printf '%064d  tierone.Jenkinsfile\n' 2
    printf '%064d  vinsguru_jenkins-pipeline.Jenkinsfile\n' 3
  } > "$path"
}

oracle_row() {
  local file=$1 compiled=$2 reached=$3
  printf '%s\tfixture/repo\t0\t1\tnot_declarative_pipeline\tfixture\tfixture\t1.0\t%s\t%s\tparsed\t0\t0\trejected\t0\t-\r\n' \
    "$file" "$compiled" "$reached"
}

write_oracle() {
  local path=$1
  {
    printf 'file\trepo\tstars\tbytes\tjenkins_lint\tjenkins_job_raw\tjenkins_job\tjenkins_elapsed_ms\tjenkins_compiled\tjenkins_reached_agent\tchengis\tchengis_stages\tchengis_steps\tranvil\tranvil_actions\tranvil_errors\r\n'
    oracle_row vinsguru_jenkins-pipeline.Jenkinsfile True False
    oracle_row notready.Jenkinsfile False False
    oracle_row ready.Jenkinsfile True True
    oracle_row tierone.Jenkinsfile False False
  } > "$path"
}

write_baseline() {
  local path=$1 repo=$2 commit=$3 oracle=$4 count=${5:-4} compiled=${6:-2} reached=${7:-1}
  local tree ledger_sha corpus_sha oracle_sha
  tree=$(git -C "$repo" rev-parse "$commit^{tree}")
  ledger_sha=$(git -C "$repo" show "$commit:docs/COMPATIBILITY-LEDGER.tsv" | sha256sum | awk '{print $1}')
  corpus_sha=$(sha256 "$repo/corpus/CORPUS-SHA256SUMS")
  oracle_sha=$(sha256 "$oracle")
  printf '{"schema_version":1,"baseline_commit":"%s","baseline_tree":"%s","baseline_ledger_sha256":"%s","corpus_manifest_sha256":"%s","corpus_file_count":%s,"jenkins_core":"2.568.1","jenkins_oracle_sha256":"%s","jenkins_compiled_count":%s,"jenkins_reached_agent_count":%s}\n' \
    "$commit" "$tree" "$ledger_sha" "$corpus_sha" "$count" "$oracle_sha" "$compiled" "$reached" > "$path"
}

baseline_for_oracle() {
  local source=$1 output=$2 oracle=$3 compiled=${4:-2} reached=${5:-1}
  local digest
  digest=$(sha256 "$oracle")
  sed -e "s/\"jenkins_oracle_sha256\":\"[0-9a-f]*\"/\"jenkins_oracle_sha256\":\"$digest\"/" \
      -e "s/\"jenkins_compiled_count\":[0-9]*/\"jenkins_compiled_count\":$compiled/" \
      -e "s/\"jenkins_reached_agent_count\":[0-9]*/\"jenkins_reached_agent_count\":$reached/" \
      "$source" > "$output"
}

baseline_for_corpus() {
  local source=$1 output=$2 manifest=$3 count=${4:-4}
  local digest
  digest=$(sha256 "$manifest")
  sed -e "s/\"corpus_manifest_sha256\":\"[0-9a-f]*\"/\"corpus_manifest_sha256\":\"$digest\"/" \
      -e "s/\"corpus_file_count\":[0-9]*/\"corpus_file_count\":$count/" \
      "$source" > "$output"
}

cp -p "$CHECKER" "$REPO/scripts/check-compatibility-regression.py"
printf '#!/bin/sh\nprintf "ran\\n" >> "%s"\n[ ! -e "%s" ]\n' "$SCORECARD_MARKER" "$OUT/scorecard-refuse" > "$REPO/scripts/generate-scorecard.bb"
chmod +x "$REPO/scripts/generate-scorecard.bb"
write_ledger "$REPO/docs/COMPATIBILITY-LEDGER.tsv" 3 admitted 1 admitted
write_manifest "$REPO/corpus/CORPUS-SHA256SUMS"
git -C "$REPO" init -q
git -C "$REPO" config user.name fogell-proof
git -C "$REPO" config user.email fogell-proof@example.invalid
git -C "$REPO" add scripts docs corpus
git -C "$REPO" commit -q -m baseline
BASE_COMMIT=$(git -C "$REPO" rev-parse HEAD)
write_oracle "$ORACLE"
write_baseline "$BASELINE" "$REPO" "$BASE_COMMIT" "$ORACLE"
printf 'candidate\n' > "$REPO/candidate.txt"
git -C "$REPO" add candidate.txt
git -C "$REPO" commit -q -m candidate

run_gate() {
  local repo=$1 baseline=$2 oracle=$3 log=$4
  shift 4
  set +e
  env FOGELL_CORPUS="$MOUNT" FOGELL_REGRESSION_BASELINE="$baseline" FOGELL_JENKINS_ORACLE="$oracle" "$@" \
    "$repo/scripts/check-compatibility-regression.py" > "$log" 2>&1
  RC=$?
  set -e
}

expect_pass() {
  local label=$1 repo=$2 baseline=$3 oracle=$4
  shift 4
  rm -f "$SCORECARD_MARKER"
  run_gate "$repo" "$baseline" "$oracle" "$OUT/run.log" "$@"
  if [ "$RC" -ne 0 ] || ! grep -Fq 'FG-094 COMPATIBILITY REGRESSION GATE PASSED:' "$OUT/run.log" || [ ! -f "$SCORECARD_MARKER" ]; then
    echo "  FAIL: $label did not pass after scorecard check"
    sed 's/^/    | /' "$OUT/run.log"
    FAILED=1
  else
    echo "  passed $label"
  fi
}

expect_reject() {
  local label=$1 repo=$2 baseline=$3 oracle=$4 wanted=$5
  shift 5
  rm -f "$SCORECARD_MARKER"
  run_gate "$repo" "$baseline" "$oracle" "$OUT/run.log" "$@"
  if [ "$RC" -eq 0 ] || ! grep -Fq "$wanted" "$OUT/run.log"; then
    echo "  FAIL: $label was not refused for: $wanted"
    sed 's/^/    | /' "$OUT/run.log"
    FAILED=1
  else
    echo "  rejected $label"
  fi
}

clone_case() {
  CASE="$LAB/case-$1"
  git clone -q "$REPO" "$CASE"
  git -C "$CASE" config user.name fogell-proof
  git -C "$CASE" config user.email fogell-proof@example.invalid
  CASE_BASELINE="$OUT/case-$1-baseline.json"
  CASE_ORACLE="$OUT/case-$1-oracle.tsv"
  cp "$BASELINE" "$CASE_BASELINE"
  cp "$ORACLE" "$CASE_ORACLE"
}

commit_ledger() {
  local repo=$1
  git -C "$repo" add docs/COMPATIBILITY-LEDGER.tsv
  git -C "$repo" commit -q -m ledger-change
}

echo '=== FG-094 positive set controls ==='
expect_pass 'exact baseline' "$REPO" "$BASELINE" "$ORACLE"

clone_case manifest_order
sed -i '1{h;d};2{G}' "$CASE/corpus/CORPUS-SHA256SUMS"
git -C "$CASE" add corpus/CORPUS-SHA256SUMS
git -C "$CASE" commit -q -m manifest-order
baseline_for_corpus "$CASE_BASELINE" "$OUT/manifest-order-baseline.json" "$CASE/corpus/CORPUS-SHA256SUMS"
expect_pass 'out-of-order unique corpus manifest' "$CASE" "$OUT/manifest-order-baseline.json" "$CASE_ORACLE"

expect_pass 'hostile inherited Git environment is ignored' "$REPO" "$BASELINE" "$ORACLE" \
  GIT_DIR=/hostile/git-dir GIT_WORK_TREE=/hostile/work-tree GIT_INDEX_FILE=/hostile/index \
  GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.ignoreCase GIT_CONFIG_VALUE_0=true

clone_case gain
write_ledger "$CASE/docs/COMPATIBILITY-LEDGER.tsv" admitted admitted 1 admitted
commit_ledger "$CASE"
expect_pass 'accepted-set gain' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE"

clone_case promotion
write_ledger "$CASE/docs/COMPATIBILITY-LEDGER.tsv" 3 1 1 admitted
commit_ledger "$CASE"
expect_pass 'admitted to tier-1 promotion' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE"

clone_case vinsguru
write_ledger "$CASE/docs/COMPATIBILITY-LEDGER.tsv" 3 admitted 1 3
commit_ledger "$CASE"
expect_pass 'vinsguru compiled-but-not-reached accepted loss' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE"

echo '=== FG-094 forbidden set regressions ==='
clone_case ready_loss
write_ledger "$CASE/docs/COMPATIBILITY-LEDGER.tsv" 3 3 1 admitted
commit_ledger "$CASE"
expect_reject 'reached-agent accepted loss' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'accepted filename set decreased for a reached_agent=True Jenkinsfile'

clone_case same_count_swap
write_ledger "$CASE/docs/COMPATIBILITY-LEDGER.tsv" admitted 3 1 admitted
commit_ledger "$CASE"
expect_reject 'same-count accepted swap' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'accepted filename set decreased for a reached_agent=True Jenkinsfile'

clone_case tier1_loss
write_ledger "$CASE/docs/COMPATIBILITY-LEDGER.tsv" 3 admitted admitted admitted
commit_ledger "$CASE"
expect_reject 'oracle-not-ready tier-1 loss' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'tier-1 filename set decreased'

clone_case tier1_swap
write_ledger "$CASE/docs/COMPATIBILITY-LEDGER.tsv" 3 1 admitted admitted
commit_ledger "$CASE"
expect_reject 'same-count tier-1 swap' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'tier-1 filename set decreased'

echo '=== FG-094 schema, binding, and environment refusals ==='
clone_case missing_row
sed -i '/^notready\.Jenkinsfile\t/d' "$CASE/docs/COMPATIBILITY-LEDGER.tsv"
commit_ledger "$CASE"
expect_reject 'missing current ledger row' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'filename sets differ'

clone_case duplicate_row
ledger_row ready.Jenkinsfile admitted >> "$CASE/docs/COMPATIBILITY-LEDGER.tsv"
commit_ledger "$CASE"
expect_reject 'duplicate current ledger row' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'filenames must be sorted and unique'

BAD_BASELINE="$OUT/bad-baseline.json"
sed 's/"schema_version":1/"schema_version":true/' "$BASELINE" > "$BAD_BASELINE"
expect_reject 'boolean schema version' "$REPO" "$BAD_BASELINE" "$ORACLE" 'schema_version must be the JSON integer 1'

sed 's/"baseline_tree":"[0-9a-f]*"/"baseline_tree":"0000000000000000000000000000000000000000"/' "$BASELINE" > "$BAD_BASELINE"
expect_reject 'wrong baseline tree' "$REPO" "$BAD_BASELINE" "$ORACLE" 'baseline tree does not match baseline commit'

sed 's/"jenkins_oracle_sha256":"[0-9a-f]*"/"jenkins_oracle_sha256":"0000000000000000000000000000000000000000000000000000000000000000"/' "$BASELINE" > "$BAD_BASELINE"
expect_reject 'wrong oracle digest' "$REPO" "$BAD_BASELINE" "$ORACLE" 'Jenkins oracle SHA-256 does not match baseline'

cp "$BASELINE" "$REPO/inside-baseline.json"
expect_reject 'baseline inside checkout' "$REPO" "$REPO/inside-baseline.json" "$ORACLE" 'baseline must be external to the checkout'
rm -f "$REPO/inside-baseline.json"

ln -s "$BASELINE" "$OUT/baseline-link.json"
expect_reject 'symlink baseline' "$REPO" "$OUT/baseline-link.json" "$ORACLE" 'baseline is not a regular non-symlink file'

cp "$BASELINE" "$OUT/oversized-baseline.json"
dd if=/dev/zero bs=17000 count=1 >> "$OUT/oversized-baseline.json" 2>/dev/null
expect_reject 'oversized baseline' "$REPO" "$OUT/oversized-baseline.json" "$ORACLE" 'baseline exceeds 16384 bytes'

sed 's/{/{"schema_version":1,/' "$BASELINE" > "$BAD_BASELINE"
expect_reject 'duplicate baseline key' "$REPO" "$BAD_BASELINE" "$ORACLE" 'baseline contains a duplicate JSON key'

sed 's/}$/,"unknown":"field"}/' "$BASELINE" > "$BAD_BASELINE"
expect_reject 'extra baseline key' "$REPO" "$BAD_BASELINE" "$ORACLE" 'baseline keys do not exactly match schema version 1'

ORPHAN=$(git -C "$REPO" commit-tree "$BASE_COMMIT^{tree}" -m orphan)
ORPHAN_TREE=$(git -C "$REPO" rev-parse "$ORPHAN^{tree}")
sed -e "s/\"baseline_commit\":\"[0-9a-f]*\"/\"baseline_commit\":\"$ORPHAN\"/" \
    -e "s/\"baseline_tree\":\"[0-9a-f]*\"/\"baseline_tree\":\"$ORPHAN_TREE\"/" "$BASELINE" > "$BAD_BASELINE"
expect_reject 'non-ancestor baseline commit' "$REPO" "$BAD_BASELINE" "$ORACLE" 'baseline commit is not an ancestor of current HEAD'

sed 's/"baseline_ledger_sha256":"[0-9a-f]*"/"baseline_ledger_sha256":"0000000000000000000000000000000000000000000000000000000000000000"/' "$BASELINE" > "$BAD_BASELINE"
expect_reject 'wrong historical ledger digest' "$REPO" "$BAD_BASELINE" "$ORACLE" 'historical baseline ledger SHA-256 does not match baseline'

sed 's/"corpus_manifest_sha256":"[0-9a-f]*"/"corpus_manifest_sha256":"0000000000000000000000000000000000000000000000000000000000000000"/' "$BASELINE" > "$BAD_BASELINE"
expect_reject 'wrong corpus manifest digest' "$REPO" "$BAD_BASELINE" "$ORACLE" 'corpus manifest SHA-256 does not match baseline'

LF_ORACLE="$OUT/oracle-lf.tsv"
tr -d '\r' < "$ORACLE" > "$LF_ORACLE"
baseline_for_oracle "$BASELINE" "$BAD_BASELINE" "$LF_ORACLE"
expect_reject 'LF-only oracle' "$REPO" "$BAD_BASELINE" "$LF_ORACLE" 'Jenkins oracle must use exact CRLF line endings'

HEADER_ORACLE="$OUT/oracle-bad-header.tsv"
sed '1s/^file\t/name\t/' "$ORACLE" > "$HEADER_ORACLE"
baseline_for_oracle "$BASELINE" "$BAD_BASELINE" "$HEADER_ORACLE"
expect_reject 'wrong oracle header' "$REPO" "$BAD_BASELINE" "$HEADER_ORACLE" 'exact 16-column schema'

BOOL_ORACLE="$OUT/oracle-bad-bool.tsv"
sed '/^ready\.Jenkinsfile/ s/\tTrue\tTrue\t/\ttrue\tTrue\t/' "$ORACLE" > "$BOOL_ORACLE"
baseline_for_oracle "$BASELINE" "$BAD_BASELINE" "$BOOL_ORACLE"
expect_reject 'nonexact oracle boolean' "$REPO" "$BAD_BASELINE" "$BOOL_ORACLE" 'boolean columns are not exact True/False'

IMPLY_ORACLE="$OUT/oracle-reached-without-compiled.tsv"
sed '/^ready\.Jenkinsfile/ s/\tTrue\tTrue\t/\tFalse\tTrue\t/' "$ORACLE" > "$IMPLY_ORACLE"
baseline_for_oracle "$BASELINE" "$BAD_BASELINE" "$IMPLY_ORACLE" 1 1
expect_reject 'reached without compiled oracle row' "$REPO" "$BAD_BASELINE" "$IMPLY_ORACLE" 'reached_agent=True without compiled=True'

clone_case ledger_schema
sed -i '/^ready\.Jenkinsfile\t/ s/$/\textra/' "$CASE/docs/COMPATIBILITY-LEDGER.tsv"
commit_ledger "$CASE"
expect_reject 'current ledger extra column' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'exactly four columns'

clone_case corpus_schema
sed -i '1s/  / /' "$CASE/corpus/CORPUS-SHA256SUMS"
git -C "$CASE" add corpus/CORPUS-SHA256SUMS
git -C "$CASE" commit -q -m corpus-schema
baseline_for_corpus "$CASE_BASELINE" "$OUT/corpus-schema-baseline.json" "$CASE/corpus/CORPUS-SHA256SUMS"
expect_reject 'corpus manifest malformed row' "$CASE" "$OUT/corpus-schema-baseline.json" "$CASE_ORACLE" 'corpus manifest row violates the exact schema'

clone_case corpus_duplicate
sed -n '1p' "$CASE/corpus/CORPUS-SHA256SUMS" >> "$CASE/corpus/CORPUS-SHA256SUMS"
git -C "$CASE" add corpus/CORPUS-SHA256SUMS
git -C "$CASE" commit -q -m corpus-duplicate
baseline_for_corpus "$CASE_BASELINE" "$OUT/corpus-duplicate-baseline.json" "$CASE/corpus/CORPUS-SHA256SUMS" 5
expect_reject 'duplicate corpus manifest filename' "$CASE" "$OUT/corpus-duplicate-baseline.json" "$CASE_ORACLE" 'corpus manifest filenames must be unique'

set +e
env -u FOGELL_REGRESSION_BASELINE -u FOGELL_JENKINS_ORACLE \
  FOGELL_CORPUS="$MOUNT" "$REPO/scripts/check-compatibility-regression.py" > "$OUT/missing-env.log" 2>&1
MISSING_ENV_RC=$?
set -e
if [ "$MISSING_ENV_RC" -eq 0 ] || ! grep -Fq 'required external baseline and Jenkins oracle are not configured' "$OUT/missing-env.log"; then
  echo '  FAIL: corpus host accepted missing baseline/oracle configuration'; FAILED=1
else
  echo '  rejected missing corpus-host baseline/oracle configuration'
fi

set +e
env -u FOGELL_JENKINS_ORACLE FOGELL_CORPUS="$MOUNT" \
  FOGELL_REGRESSION_BASELINE="$BASELINE" "$REPO/scripts/check-compatibility-regression.py" > "$OUT/partial-env.log" 2>&1
PARTIAL_ENV_RC=$?
set -e
if [ "$PARTIAL_ENV_RC" -eq 0 ] || ! grep -Fq 'must be supplied together' "$OUT/partial-env.log"; then
  echo '  FAIL: corpus host accepted partial baseline/oracle configuration'; FAILED=1
else
  echo '  rejected partial corpus-host configuration'
fi

NO_CORPUS="$LAB/no-corpus"
set +e
FOGELL_CORPUS="$NO_CORPUS" "$REPO/scripts/check-compatibility-regression.py" > "$OUT/no-corpus.log" 2>&1
NO_CORPUS_RC=$?
set -e
if [ "$NO_CORPUS_RC" -ne 0 ] || ! grep -Fq 'NOT RUN: corpus is not mounted' "$OUT/no-corpus.log"; then
  echo '  FAIL: no-corpus host did not report its explicit skip'; FAILED=1
else
  echo '  reported explicit no-corpus skip'
fi

touch "$OUT/scorecard-refuse"
printf '{broken\n' > "$BAD_BASELINE"
expect_reject 'scorecard failure precedes malformed baseline comparison' "$REPO" "$BAD_BASELINE" "$ORACLE" 'generate-scorecard.bb --check failed before regression comparison'
rm -f "$OUT/scorecard-refuse"

echo '=== FG-094 direct checker mutations ==='
mutant_case() {
  local label=$1
  clone_case "mutant-$label"
  MUTANT="$CASE"
  MUTANT_CHECKER="$MUTANT/scripts/check-compatibility-regression.py"
  MUTANT_BASELINE="$CASE_BASELINE"
  MUTANT_ORACLE="$CASE_ORACLE"
}

commit_mutant() {
  local repo=$1 label=$2 before=$3
  local after
  after=$(sha256 "$repo/scripts/check-compatibility-regression.py")
  if [ "$before" = "$after" ]; then
    echo "  FAIL: $label mutation changed nothing"; FAILED=1; return 1
  fi
  git -C "$repo" add scripts/check-compatibility-regression.py
  git -C "$repo" commit -q -m "mutate $label"
}

mutant_case counts_only
BEFORE=$(sha256 "$MUTANT_CHECKER")
sed -i 's/if not baseline\.tier1 <= current\.tier1:/if len(current.tier1) < len(baseline.tier1):/; s/if not oracle_ready_baseline <= current\.accepted:/if len(current.accepted) < len(baseline.accepted):/' "$MUTANT_CHECKER"
commit_mutant "$MUTANT" counts-only "$BEFORE"
write_ledger "$MUTANT/docs/COMPATIBILITY-LEDGER.tsv" admitted 3 1 admitted
commit_ledger "$MUTANT"
expect_pass 'counts-only mutant exposes same-count accepted swap' "$MUTANT" "$MUTANT_BASELINE" "$MUTANT_ORACLE"

mutant_case compiled_oracle
BEFORE=$(sha256 "$MUTANT_CHECKER")
sed -i 's/oracle\.reached_by_file\[name\]/name in oracle.compiled/' "$MUTANT_CHECKER"
commit_mutant "$MUTANT" compiled-vs-reached "$BEFORE"
write_ledger "$MUTANT/docs/COMPATIBILITY-LEDGER.tsv" 3 admitted 1 3
commit_ledger "$MUTANT"
expect_reject 'compiled-vs-reached mutant on vinsguru control' "$MUTANT" "$MUTANT_BASELINE" "$MUTANT_ORACLE" 'accepted filename set decreased'

mutant_case tier1_omission
BEFORE=$(sha256 "$MUTANT_CHECKER")
sed -i '/if not baseline\.tier1 <= current\.tier1:/,+1 s/^/    # FG-094 planted tier1 omission: /' "$MUTANT_CHECKER"
commit_mutant "$MUTANT" tier1-omission "$BEFORE"
write_ledger "$MUTANT/docs/COMPATIBILITY-LEDGER.tsv" 3 admitted admitted admitted
commit_ledger "$MUTANT"
expect_pass 'tier1-set omission mutant exposes oracle-not-ready tier1 loss' "$MUTANT" "$MUTANT_BASELINE" "$MUTANT_ORACLE"

mutant_case missing_default
BEFORE=$(sha256 "$MUTANT_CHECKER")
sed -i '/require_equal_file_sets(corpus_files/d; s/oracle\.reached_by_file\[name\]/oracle.reached_by_file.get(name, False)/' "$MUTANT_CHECKER"
commit_mutant "$MUTANT" missing-row-default "$BEFORE"
sed '/^vinsguru_jenkins-pipeline\.Jenkinsfile/d' "$MUTANT_ORACLE" > "$OUT/oracle-without-vins.tsv"
mv "$OUT/oracle-without-vins.tsv" "$MUTANT_ORACLE"
write_baseline "$MUTANT_BASELINE" "$MUTANT" "$BASE_COMMIT" "$MUTANT_ORACLE" 4 1 1
expect_pass 'missing-row default mutant exposes absent oracle row' "$MUTANT" "$MUTANT_BASELINE" "$MUTANT_ORACLE"

mutant_case git_replace
BEFORE=$(sha256 "$MUTANT_CHECKER")
sed -i '/"GIT_NO_REPLACE_OBJECTS": "1",/d' "$MUTANT_CHECKER"
commit_mutant "$MUTANT" replacement-sanitization "$BEFORE"
REPLACEMENT=$(git -C "$MUTANT" commit-tree "HEAD^{tree}" -m replacement)
git -C "$MUTANT" replace "$BASE_COMMIT" "$REPLACEMENT"
expect_reject 'replacement-sanitization mutant' "$MUTANT" "$MUTANT_BASELINE" "$MUTANT_ORACLE" 'baseline tree does not match baseline commit'

clone_case suffix_permissiveness
sed -i '/^notready\.Jenkinsfile\t/i bad.Jenkinsfile.extra\t3\tmalformed_syntax\trefused at 1:1' "$CASE/docs/COMPATIBILITY-LEDGER.tsv"
sed -i '1i 0000000000000000000000000000000000000000000000000000000000000004  bad.Jenkinsfile.extra' "$CASE/corpus/CORPUS-SHA256SUMS"
oracle_row bad.Jenkinsfile.extra False False >> "$CASE_ORACLE"
git -C "$CASE" add docs/COMPATIBILITY-LEDGER.tsv corpus/CORPUS-SHA256SUMS
git -C "$CASE" commit -q -m suffix-baseline
SUFFIX_BASE=$(git -C "$CASE" rev-parse HEAD)
write_baseline "$CASE_BASELINE" "$CASE" "$SUFFIX_BASE" "$CASE_ORACLE" 5 2 1
expect_reject 'malformed filename suffix' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'malformed Jenkinsfile name'
BEFORE=$(sha256 "$CASE/scripts/check-compatibility-regression.py")
sed -i 's/if not FILENAME_RE\.fullmatch(filename):/if False:  # FG-094 planted suffix-permissiveness mutation/' "$CASE/scripts/check-compatibility-regression.py"
commit_mutant "$CASE" suffix-permissiveness "$BEFORE"
expect_pass 'suffix-permissiveness mutant exposes malformed shared filename' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE"

clone_case schema_permissiveness
sed -i '/^ready\.Jenkinsfile\t/ s/$/\textra/' "$CASE/docs/COMPATIBILITY-LEDGER.tsv"
git -C "$CASE" add docs/COMPATIBILITY-LEDGER.tsv
git -C "$CASE" commit -q -m schema-baseline
SCHEMA_BASE=$(git -C "$CASE" rev-parse HEAD)
write_baseline "$CASE_BASELINE" "$CASE" "$SCHEMA_BASE" "$CASE_ORACLE"
expect_reject 'historical ledger extra column' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE" 'exactly four columns'
BEFORE=$(sha256 "$CASE/scripts/check-compatibility-regression.py")
sed -i 's/if len(fields) != 4:/if len(fields) < 4:  # FG-094 planted schema-permissiveness mutation/' "$CASE/scripts/check-compatibility-regression.py"
commit_mutant "$CASE" schema-permissiveness "$BEFORE"
expect_pass 'schema-permissiveness mutant exposes extra ledger column' "$CASE" "$CASE_BASELINE" "$CASE_ORACLE"

if [ "$FAILED" -ne 0 ]; then
  echo 'FG-094 compatibility regression proof FAILED'
  exit 1
fi
echo 'FG-094 compatibility regression proof PASSED'
