FROM mcr.microsoft.com/dotnet/sdk@sha256:493fca072aac81307027cbb7b7c9a82b6e87d222af315504d05dc6530e69b519
RUN apt-get update && apt-get install -y --no-install-recommends python3 procps \
    && rm -rf /var/lib/apt/lists/*
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 DOTNET_NOLOGO=1
WORKDIR /app
